version: '3.8'
services:
  front:
    image: homepage-front
    container_name: homepage-front
    ports:
      - '3000:3000'
    build:
      context: .
      dockerfile: dockerfile
    stdin_open: true
    tty: true
    volumes:
      - .:/app
